version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: nemo_pub_app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      # при использовании внешнего Postgres оставь только DATABASE_URL в .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # важно: используем process.env.PORT, а не ${PORT}
      test: ["CMD", "node", "-e", "fetch(`http://localhost:${process.env.PORT||3000}/health`).then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: ["npm", "run", "start"]  # start -> node dist/server/bootstrap.js

  db:
    image: postgres:15
    container_name: nemo_pub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nemo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nemo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
